go_import_path: github.com/azmodb/ninep
language: go
go:
  - 1.12.x

services:
   - docker
before_install:
   - bash scripts/docker-diod.bash
script:
   - go test -tags=compat -v ./...

#script:
    #- go test -v ./...
