// THIS FILE IS AUTOMATICALLY GENERATED by `go run internal/generator.go`.
// EDIT legacy.go INSTEAD.

package proto

import "math"

var generatedLegacyPackets = []packet{
	{&Tversion{}, &Tversion{}},
	{&Tversion{MessageSize: math.MaxUint32, Version: string16.String()}, &Tversion{}},
	{&Rversion{}, &Rversion{}},
	{&Rversion{MessageSize: math.MaxUint32, Version: string16.String()}, &Rversion{}},
	{&Tflush{}, &Tflush{}},
	{&Tflush{OldTag: math.MaxUint16}, &Tflush{}},
	{&Rflush{}, &Rflush{}},
	{&Tread{}, &Tread{}},
	{&Tread{Fid: math.MaxUint32, Offset: math.MaxUint64, Count: math.MaxUint32}, &Tread{}},
	{&Rwrite{}, &Rwrite{}},
	{&Rwrite{Count: math.MaxUint32}, &Rwrite{}},
	{&Tclunk{}, &Tclunk{}},
	{&Tclunk{Fid: math.MaxUint32}, &Tclunk{}},
	{&Rclunk{}, &Rclunk{}},
	{&Tremove{}, &Tremove{}},
	{&Tremove{Fid: math.MaxUint32}, &Tremove{}},
	{&Rremove{}, &Rremove{}},
}
