// THIS FILE IS AUTOMATICALLY GENERATED by `go run internal/generator.go`.
// EDIT legacy.go, linux.go INSTEAD.

package proto

import (
	"sync"

	"github.com/azmodb/pkg/pool"
)

var allocator = pool.Map{
	MessageTversion: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tversion{}, Rx: &Rversion{}}
	}},
	MessageTflush: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tflush{}, Rx: &Rflush{}}
	}},
	MessageTwalk: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Twalk{}, Rx: &Rwalk{}}
	}},
	MessageTread: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tread{}, Rx: &Rread{}}
	}},
	MessageTwrite: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Twrite{}, Rx: &Rwrite{}}
	}},
	MessageTclunk: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tclunk{}, Rx: &Rclunk{}}
	}},
	MessageTremove: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tremove{}, Rx: &Rremove{}}
	}},
	MessageTlauth: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tlauth{}, Rx: &Rlauth{}}
	}},
	MessageTlattach: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tlattach{}, Rx: &Rlattach{}}
	}},
	MessageTstatfs: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tstatfs{}, Rx: &Rstatfs{}}
	}},
	MessageTlopen: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tlopen{}, Rx: &Rlopen{}}
	}},
	MessageTlcreate: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tlcreate{}, Rx: &Rlcreate{}}
	}},
	MessageTsymlink: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tsymlink{}, Rx: &Rsymlink{}}
	}},
	MessageTmknod: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tmknod{}, Rx: &Rmknod{}}
	}},
	MessageTrename: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Trename{}, Rx: &Rrename{}}
	}},
	MessageTreadlink: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Treadlink{}, Rx: &Rreadlink{}}
	}},
	MessageTgetattr: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tgetattr{}, Rx: &Rgetattr{}}
	}},
	MessageTsetattr: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tsetattr{}, Rx: &Rsetattr{}}
	}},
	MessageTxattrwalk: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Txattrwalk{}, Rx: &Rxattrwalk{}}
	}},
	MessageTxattrcreate: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Txattrcreate{}, Rx: &Rxattrcreate{}}
	}},
	MessageTreaddir: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Treaddir{}, Rx: &Rreaddir{}}
	}},
	MessageTfsync: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tfsync{}, Rx: &Rfsync{}}
	}},
	MessageTlock: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tlock{}, Rx: &Rlock{}}
	}},
	MessageTgetlock: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tgetlock{}, Rx: &Rgetlock{}}
	}},
	MessageTlink: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tlink{}, Rx: &Rlink{}}
	}},
	MessageTmkdir: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tmkdir{}, Rx: &Rmkdir{}}
	}},
	MessageTrenameat: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Trenameat{}, Rx: &Rrenameat{}}
	}},
	MessageTunlinkat: &sync.Pool{New: func() interface{} {
		return &Fcall{Tx: &Tunlinkat{}, Rx: &Runlinkat{}}
	}},
}
