// Code generated by "stringer -type FcallType -output strings.go"; DO NOT EDIT.

package proto

import "strconv"

const _FcallType_name = "TversionRversionTauthRauthTattachRattachTerrorRerrorTflushRflushTwalkRwalkTopenRopenTcreateRcreateTreadRreadTwriteRwriteTclunkRclunkTremoveRremoveTstatRstatTwstatRwstat"

var _FcallType_index = [...]uint8{0, 8, 16, 21, 26, 33, 40, 46, 52, 58, 64, 69, 74, 79, 84, 91, 98, 103, 108, 114, 120, 126, 132, 139, 146, 151, 156, 162, 168}

func (i FcallType) String() string {
	i -= 100
	if i >= FcallType(len(_FcallType_index)-1) {
		return "FcallType(" + strconv.FormatInt(int64(i+100), 10) + ")"
	}
	return _FcallType_name[_FcallType_index[i]:_FcallType_index[i+1]]
}
